apiVersion: v1
kind: Secret
metadata:
  name: calculator-secret
  namespace: {{ .Values.namespace }}
data:
  MSSQL_SA_PASSWORD: {{ .Values.db.password }}
  CALC_DB_CONNECTIONSTRING: {{ .Values.api.connectionString }}
