apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api-dep
  namespace: {{ .Values.namespace }}
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: calculator-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/calculator-cm.yaml") . | sha256sum }}    
{{ if .Values.dapr }}
        dapr.io/enabled: "true"
        dapr.io/app-id: "calculator-api"
        dapr.io/app-port: "80"
        dapr.io/enable-api-logging: "true"
{{ end }}
      labels:
        tier: calculator-api
    spec:
      containers:
      - name: calculator-api
        image: {{ .Values.repo }}/calculator-api:{{ .Values.api.tag }}
        ports:
        - containerPort: 80
        env:
        - name: CALC_DB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: calculator-secret
              key: CALC_DB_CONNECTIONSTRING
{{ if .Values.api.execute }}
        - name: CALC_EXECUTEAPI_BASEURL
          value: {{ .Values.api.execute.apiBaseUrl }}
{{ end }}
{{ if .Values.api.log }}
        - name: CALC_LOGAPI_BASEURL
          value: {{ .Values.api.log.apiBaseUrl }}
{{ end }}
{{ if .Values.dapr }}
        - name: DAPR_STATESTORE_URL
          value: {{ .Values.dapr.stateStoreUrl }}
        - name: USE_DAPR_STATE
          value: "{{ .Values.dapr.useDaprState }}"
{{ if .Values.dapr.pubSubUrl }}
        - name: DAPR_PUBSUB_URL
          value: {{ .Values.dapr.pubSubUrl }}
{{ end }}
{{ end }}
        imagePullPolicy: Always

