apiVersion: v1
kind: Service
metadata:
  name: calculator-db-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    tier: calculator-db
  ports:
    - protocol: TCP
{{- if eq .Values.db.serviceType "NodePort" }}
      nodePort: {{ .Values.db.nodePort }}
      port: 1433
{{ end }}
{{- if eq .Values.db.serviceType "LoadBalancer" }}
      port: {{ .Values.db.servicePort }}
{{ end }}
{{- if eq .Values.db.serviceType "ClusterIP" }}
      port: {{ .Values.db.servicePort }}
{{ end }}
      targetPort: 1433
  type: {{ .Values.db.serviceType }} # LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-db-cip
  namespace: {{ .Values.namespace }}
spec:
  selector:
    tier: calculator-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP