apiVersion: v1
kind: Service
metadata:
  name: calculator-db-cip
  namespace: calculator
spec:
  selector:
    tier: calculator-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
