apiVersion: v1
kind: Service
metadata:
  name: calculator-api-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: calculator
spec:
  selector:
    tier: calculator-api
  ports:
    - protocol: TCP
{{- if eq .Values.api.serviceType "NodePort" }}
      nodePort: {{ .Values.api.nodePort }}
      port: 80
{{ end }}
{{- if eq .Values.api.serviceType "LoadBalancer" }}
      port: {{ .Values.api.servicePort }}
{{ end }}
      targetPort: 80
      name: http
  type: {{ .Values.api.serviceType }}
