{{ if .Values.api.log }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-log-api-dep
  namespace: {{ .Values.namespace }}
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: calculator-log-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/calculator-cm.yaml") . | sha256sum }}
{{ if .Values.dapr.pubSubUrl }}
        dapr.io/enabled: "true"
        dapr.io/app-id: "calculator-log-api"
        dapr.io/app-port: "80"
{{ end }}
      labels:
        tier: calculator-log-api
    spec:
      containers:
      - name: calculator-log-api
        image: {{ .Values.repo }}/calculator-log-api:{{ .Values.api.log.tag }}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: CALC_DB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: calculator-secret
              key: CALC_DB_CONNECTIONSTRING
{{ end }}
