trigger:
  none

stages:
- stage: Validate_Publish_ARM_Template
  variables:
  - group: zipzapp-metadata
  jobs:
  - template: templates/validate-publish-ARM-template.yml
    parameters: 
      azureSubscription: 'Visual Studio Professional'
      resourceGroup: $(resourceGroup)
      location: $(location)
      armTemplate: $(webAppArmTemplate)
- stage: Deploy_Web_App_Dev
  variables:
  - group: calculator-dev
  jobs:
  - template: templates/deploy-web-app-infra.yml
    parameters:
      azureSubscription: 'Visual Studio Professional'
      resourceGroup: $(resourceGroup)
      location: $(location)
      webAppArmTemplate: $(webAppArmTemplate)
      planName: $(planName)
      appName: $(appName)
      skuName: $(skuName)
      skuCapacity: $(skuCapacity)
