apiVersion: v1
kind: Service
metadata:
  name: calculator-api-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: calculator
spec:
  selector:
    tier: calculator-api
  ports:
    - protocol: TCP
      port: {{ .Values.api.servicePort }}
      targetPort: 80
      name: http
  type: {{ .Values.api.serviceType }}
