apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: calculator-spc # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: {{ .Values.workloadIdentityId }} # Setting this to use workload identity
    keyvaultName: {{ .Values.kvName }}       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: Settings--CalcDbConnectionString
          objectType: secret              
          objectVersion: ""               
    tenantId: {{ .Values.tenantId }}        # The tenant ID of the key vault
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: CALC_DB_CONNECTIONSTRING
      objectName: Settings--CalcDbConnectionString
    secretName: settings--calcdbconnectionstring
    type: Opaque
